#!/usr/bin/env bash

# Get the commit message (first argument is the file containing the message)
MSG_FILE=$1

# Run commitlint using nix develop
nix develop .#commitlint --command bash -c "commitlint --edit $MSG_FILE --config \$COMMITLINT_CONFIG"
